name: kidpro
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python
  - wsidata
  - lazyslide
  - ipywidgets
  - pytorch
  - matplotlib
  - ipykernel
  - mlflow
  - numpy
  - pandas
  - openslide-python
  - monai
  - scikit-image
  - albumentations
  - opencv-python
  - einops
  - fairscale
  - segmentation-models-pytorch
  - timm
  - peft
  - scikit-learn
  - ipykernel
  - hydra-core
  - omegaconf
  - cuda-toolkit
  - cuda-nvcc
  - flash-attn
